import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const component = readFileSync(path.join(root, "components", "intro", "FrozenLogbookIntro.tsx"), "utf8");
const globals = readFileSync(path.join(root, "app", "globals.css"), "utf8");
const layout = readFileSync(path.join(root, "app", "layout.tsx"), "utf8");

assert.match(component, /INTRO_DURATION_MS = 5200/);
assert.match(component, /INTRO_VIDEO_1080_WEBM = "\/intro\/pizza-logs-cinematic-intro-1080p.webm"/);
assert.match(component, /INTRO_VIDEO_1080_MP4 = "\/intro\/pizza-logs-cinematic-intro-1080p.mp4"/);
assert.match(component, /INTRO_VIDEO_1440_WEBM = "\/intro\/pizza-logs-cinematic-intro.webm"/);
assert.match(component, /INTRO_VIDEO_1440_MP4 = "\/intro\/pizza-logs-cinematic-intro.mp4"/);
assert.match(component, /INTRO_VIDEO_4K_WEBM = "\/intro\/pizza-logs-cinematic-intro-4k.webm"/);
assert.match(component, /INTRO_VIDEO_4K_MP4 = "\/intro\/pizza-logs-cinematic-intro-4k.mp4"/);
assert.match(component, /INTRO_VIDEO_MOBILE_WEBM = "\/intro\/pizza-logs-cinematic-intro-mobile.webm"/);
assert.match(component, /INTRO_VIDEO_MOBILE_MP4 = "\/intro\/pizza-logs-cinematic-intro-mobile.mp4"/);
assert.match(component, /INTRO_VIDEO_MOBILE_4K_WEBM = "\/intro\/pizza-logs-cinematic-intro-mobile-4k.webm"/);
assert.match(component, /INTRO_VIDEO_MOBILE_4K_MP4 = "\/intro\/pizza-logs-cinematic-intro-mobile-4k.mp4"/);
assert.match(component, /INTRO_POSTER_1080 = "\/intro\/pizza-logs-cinematic-poster-1080p.jpg"/);
assert.match(component, /INTRO_POSTER_1440 = "\/intro\/pizza-logs-cinematic-poster.jpg"/);
assert.match(component, /INTRO_POSTER_4K = "\/intro\/pizza-logs-cinematic-poster-4k.jpg"/);
assert.match(component, /INTRO_POSTER_MOBILE = "\/intro\/pizza-logs-cinematic-poster-mobile.jpg"/);
assert.match(component, /INTRO_POSTER_MOBILE_4K = "\/intro\/pizza-logs-cinematic-poster-mobile-4k.jpg"/);
assert.match(component, /MOBILE_4K_VIDEO_MEDIA = "\(max-width: 640px\) and \(min-resolution: 2.5dppx\)"/);
assert.match(component, /MOBILE_VIDEO_MEDIA = "\(max-width: 640px\)"/);
assert.match(component, /DESKTOP_4K_VIDEO_MEDIA =\s*"\(min-width: 3200px\), \(min-width: 2400px\) and \(min-resolution: 1\.5dppx\), \(min-width: 1920px\) and \(min-resolution: 2dppx\)"/);
assert.match(component, /DESKTOP_1440_VIDEO_MEDIA = "\(min-width: 2200px\), \(min-width: 1280px\) and \(min-resolution: 1\.5dppx\)"/);
assert.match(component, /VIDEO_SOURCES(?:: IntroVideoSource\[\])? = \[/);
assert.match(component, /POSTER_SOURCES(?:: IntroPosterSource\[\])? = \[/);
assert.match(component, /<video[\s\S]*className="frozen-intro-video"[\s\S]*autoPlay[\s\S]*muted[\s\S]*playsInline/);
assert.match(component, /VIDEO_SOURCES\.map/);
assert.match(component, /<source[\s\S]*media=\{source\.media\}[\s\S]*src=\{source\.src\}[\s\S]*type=\{source\.type\}/);
assert.match(component, /poster=\{poster\}/);
assert.match(component, /window\.matchMedia\(source\.media\)/);
assert.match(component, /onEnded=\{finishIntro\}/);
assert.match(component, /prefers-reduced-motion: reduce/);
assert.match(component, /setVisible\(true\)/);
assert.doesNotMatch(component, /localStorage/);
assert.doesNotMatch(component, /sessionStorage/);
assert.doesNotMatch(component, /usePathname/);
assert.doesNotMatch(component, /PARTICLES/);
assert.match(component, />\s*Skip\s*</);
assert.match(component, />\s*Pizza Logs\s*</);

assert.match(layout, /import \{ FrozenLogbookIntro \}/);
assert.match(layout, /<FrozenLogbookIntro \/>/);

assert.match(globals, /\.frozen-intro-overlay/);
assert.match(globals, /\.frozen-intro-video/);
assert.match(globals, /\.frozen-intro-vignette/);
assert.match(globals, /\.frozen-intro-brand/);
assert.match(globals, /100lvh/);
assert.match(globals, /@media \(max-width: 640px\)[\s\S]*\.frozen-intro-brand span/);
assert.match(globals, /@media \(max-width: 640px\)[\s\S]*\.frozen-intro-skip/);
assert.doesNotMatch(globals, /\.frozen-intro-particle/);
assert.match(globals, /\.reveal-item/);
assert.match(globals, /\.boss-reveal-item/);
assert.match(globals, /prefers-reduced-motion: reduce/);

console.log("frozen-intro source tests passed");
