import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const component = readFileSync(path.join(root, "components", "intro", "UploadCinematicIntro.tsx"), "utf8");
const globals = readFileSync(path.join(root, "app", "globals.css"), "utf8");
const layout = readFileSync(path.join(root, "app", "layout.tsx"), "utf8");
const uploadPage = readFileSync(path.join(root, "app", "page.tsx"), "utf8");

assert.match(component, /export const UPLOAD_INTRO_DURATION_MS = 3800/);
assert.match(component, /const REDUCED_MOTION_DURATION_MS = 350/);
assert.match(component, /export function UploadCinematicIntro/);
assert.match(component, /createPortal/);
assert.match(component, /document\.body/);
assert.match(component, /if \(!portalReady \|\| !visible\) return null/);
assert.doesNotMatch(component, /localStorage/);
assert.doesNotMatch(component, /URLSearchParams/);
assert.doesNotMatch(component, /usePathname/);
assert.doesNotMatch(component, /<img|<video|<audio|framer-motion|three/i);
assert.match(component, />\s*Skip\s*</);
assert.match(component, /keydown/);
assert.match(component, /event\.key === "Escape"/);
assert.match(component, /Frozen raid boss intro/);
assert.match(component, /frozen-aggro-figure/);
assert.match(component, /frozen-aggro-boss-aura/);
assert.match(component, /frozen-aggro-cape/);
assert.match(component, /frozen-aggro-rune-core/);
assert.match(component, /frozen-aggro-icefire/);
assert.match(component, /frozen-aggro-spires/);
assert.match(component, /frozen-aggro-front-details/);
assert.match(component, /frozen-aggro-painted-figure/);
assert.match(component, /frozen-aggro-film-grain/);
assert.match(component, /frozen-aggro-letterbox/);
assert.match(component, /frozen-aggro-cinematic-fog/);
assert.match(component, /frozen-aggro-backlight/);
assert.match(component, /frozen-aggro-closeup-silhouette/);
assert.match(component, /frozen-aggro-visor-glow/);
assert.match(component, /frozen-aggro-fur-mantle/);
assert.match(component, /frozen-aggro-mask-plate/);
assert.match(component, /frozen-aggro-rune-veins/);
assert.match(component, /frozen-aggro-eyes/);
assert.match(component, /frozen-aggro-blade/);
assert.match(component, /frozen-aggro-crack/);
assert.match(component, /frozen-aggro-shard/);
assert.match(component, /<svg/);

assert.doesNotMatch(layout, /FrozenLogbookIntro|UploadCinematicIntro|frozen-aggro/);
assert.match(uploadPage, /import \{ UploadCinematicIntro \}/);
assert.match(uploadPage, /<UploadCinematicIntro \/>/);

assert.match(globals, /\.frozen-aggro-overlay/);
assert.match(globals, /\.frozen-aggro-snow/);
assert.match(globals, /\.frozen-aggro-boss-aura/);
assert.match(globals, /\.frozen-aggro-icefire/);
assert.match(globals, /\.frozen-aggro-spires/);
assert.match(globals, /\.frozen-aggro-front-details/);
assert.match(globals, /\.frozen-aggro-painted-figure/);
assert.match(globals, /\.frozen-aggro-film-grain/);
assert.match(globals, /\.frozen-aggro-letterbox/);
assert.match(globals, /\.frozen-aggro-cinematic-fog/);
assert.match(globals, /\.frozen-aggro-backlight/);
assert.match(globals, /\.frozen-aggro-closeup-silhouette/);
assert.match(globals, /\.frozen-aggro-visor-glow/);
assert.match(globals, /\.frozen-aggro-fur-mantle/);
assert.match(globals, /\.frozen-aggro-mask-plate/);
assert.match(globals, /\.frozen-aggro-rune-veins/);
assert.match(globals, /\.frozen-aggro-figure/);
assert.match(globals, /\.frozen-aggro-eyes/);
assert.match(globals, /\.frozen-aggro-blade/);
assert.match(globals, /\.frozen-aggro-crack/);
assert.match(globals, /@keyframes frozenAggroWalk/);
assert.match(globals, /@keyframes frozenAggroCameraPush/);
assert.match(globals, /@keyframes frozenAggroTurn/);
assert.match(globals, /@keyframes frozenAggroFrontDetail/);
assert.match(globals, /@keyframes frozenAggroFogRoll/);
assert.match(globals, /@keyframes frozenAggroFilmGrain/);
assert.match(globals, /@keyframes frozenAggroFrostFire/);
assert.match(globals, /@keyframes frozenAggroSlash/);
assert.match(globals, /@keyframes frozenAggroShatter/);
assert.match(globals, /\.reveal-item/);
assert.match(globals, /\.boss-reveal-item/);
assert.match(globals, /prefers-reduced-motion: reduce/);

console.log("upload cinematic intro source tests passed");
